spring:
  application:
    name: PKB Connector
  main:
    banner-mode: off
  redis:
    host: ${REDIS_HOST:app-cache}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS:ythUIb6745zZg}
server:
  servlet:
    context-path: "/api"

logging:
  level:
    org.apache.http: ${HTTP_LOG:INFO}

app:
  pkb:
    url: '${PKB_PROTOCOL:http}://${PKB_HOST:www-test2.1cb.kz}:${PKB_PORT:80}/FCBServices/Service'
    kdnUrl: '${PKB_KDN_PROTOCOL:http}://${PKB_KDN_HOST:www-test2.1cb.kz}:${PKB_KDN_PORT:80}/kdn/kdnService'
    username: '${PKB_USERNAME:7018884245}'
    password: '${PKB_PASSWORD:911031300745}'
    connection-timeout: ${PKB_CONNECTION_TIMEOUT:60s}
    connection-pool-size: ${PKB_CONNECTION_POOL_SIZE:30}
    default-keep-alive: ${PKB_DEFAULT_KEEP_ALIVE:30s}
    credit-report-cache-ttl: ${PKB_CREDIT-REPORT-CACHE-TTL:48h}
    kdn-cache-ttl: ${PKB_KDN-CACHE-TTL:24h}
