pring:
  application:
    name: PKB Connector
  main:
    banner-mode: off
server:
  servlet:
    context-path: "/api"
app:
  pkb:
    url: '${PKB_PROTOCOL:http}://${PKB_HOST:www-test2.1cb.kz}:${PKB_PORT:80}/FCBServices/Service'
    username: '${PKB_USERNAME:7018884245}'
    password: '${PKB_PASSWORD:911031300745}'
    connection-timeout: ${COID_CONNECTION_TIMEOUT:50s}